package payloads

// GetTestPayloads returns a slice of test payloads with the tickets shuffled.
// The order of tickets within each "tickets" array is randomized,
func GetTestPayloads() []map[string]interface{} {
	payloads := []map[string]interface{}{
		{"tickets": [][]string{{"LAX", "JFK"}, {"SFO", "LAX"}}},
		{"tickets": [][]string{{"ATL", "MCO"}, {"SFO", "ATL"}, {"MCO", "JFK"}}},
		{"tickets": [][]string{{"CDG", "FCO"}, {"JFK", "LHR"}, {"FCO", "ATH"}, {"LHR", "CDG"}}},
		{"tickets": [][]string{{"LHR", "CDG"}, {"ORD", "JFK"}, {"LAX", "DFW"}, {"SFO", "LAX"}, {"DFW", "ORD"}, {"JFK", "LHR"}}},
		{"tickets": [][]string{{"SIN", "HND"}, {"LHR", "DXB"}, {"JFK", "LHR"}, {"HND", "LAX"}, {"DXB", "SIN"}}},
		{"tickets": [][]string{
			{"ZYC", "ZYD"}, {"ACS", "ACT"}, {"ZYM", "ZYN"}, {"ABW", "ABX"}, {"ZZL", "ZZM"}, {"ZZN", "ZZO"},
			{"ZYW", "ZYX"}, {"ZZH", "ZZI"}, {"ZYT", "ZYU"}, {"ZYK", "ZYL"}, {"ZZD", "ZZE"}, {"AAY", "AAZ"},
			{"ABY", "ABZ"}, {"ADY", "ADZ"}, {"ABA", "ABB"}, {"AAK", "AAL"}, {"ACL", "ACM"}, {"ACV", "ACW"},
			{"ZXW", "ZXX"}, {"ZYI", "ZYJ"}, {"ZZC", "ZZD"}, {"ACG", "ACH"}, {"ZYY", "ZYZ"}, {"ADZ", "AEA"},
			{"ADF", "ADG"}, {"AAL", "AAM"}, {"ZZB", "ZZC"}, {"AEK", "AEL"}, {"ZXX", "ZXY"}, {"AAC", "AAD"},
			{"ADQ", "ADR"}, {"ACF", "ACG"}, {"ADS", "ADT"}, {"ACP", "ACQ"}, {"ZYP", "ZYQ"}, {"ADV", "ADW"},
			{"ACR", "ACS"}, {"ABC", "ABD"}, {"AAH", "AAI"}, {"ZYS", "ZYT"}, {"AEP", "AEQ"}, {"ZZK", "ZZL"},
			{"ABL", "ABM"}, {"ABT", "ABU"}, {"AAE", "AAF"}, {"ZYU", "ZYV"}, {"ADE", "ADF"}, {"AAS", "AAT"},
			{"AAD", "AAE"}, {"ABK", "ABL"}, {"AEE", "AEF"}, {"ZZF", "ZZG"}, {"AAB", "AAC"}, {"AEN", "AEO"},
			{"ABE", "ABF"}, {"ABR", "ABS"}, {"ZYO", "ZYP"}, {"ADN", "ADO"}, {"ZZI", "ZZJ"}, {"ZXS", "ZXT"},
			{"ADH", "ADI"}, {"ZZR", "ZZS"}, {"ADT", "ADU"}, {"ZYZ", "ZZA"}, {"ABI", "ABJ"}, {"ABH", "ABI"},
			{"ADU", "ADV"}, {"ZYX", "ZYY"}, {"ZYE", "ZYF"}, {"ADX", "ADY"}, {"ZZJ", "ZZK"}, {"AED", "AEE"},
			{"ZYF", "ZYG"}, {"ACQ", "ACR"}, {"ACA", "ACB"}, {"ZYR", "ZYS"}, {"AAF", "AAG"}, {"AAX", "AAY"},
			{"ZZX", "ZZY"}, {"ADK", "ADL"}, {"ABV", "ABW"}, {"AEA", "AEB"}, {"ZXT", "ZXU"}, {"ABD", "ABE"},
			{"AEM", "AEN"}, {"ZZP", "ZZQ"}, {"AAN", "AAO"}, {"ZYG", "ZYH"}, {"AAV", "AAW"}, {"ABO", "ABP"},
			{"ABQ", "ABR"}, {"ZYL", "ZYM"}, {"AAI", "AAJ"}, {"AAG", "AAH"}, {"AEO", "AEP"}, {"ZZV", "ZZW"},
			{"ACT", "ACU"}, {"ACB", "ACC"}, {"ADA", "ADB"}, {"ADJ", "ADK"}, {"ACH", "ACI"}, {"ZZU", "ZZV"},
			{"AAP", "AAQ"}, {"ZYQ", "ZYR"}, {"ABF", "ABG"}, {"AAQ", "AAR"}, {"ABZ", "ACA"}, {"ZXU", "ZXV"},
			{"ZZS", "ZZT"}, {"ZZQ", "ZZR"}, {"ABN", "ABO"}, {"ACI", "ACJ"}, {"ZYB", "ZYC"}, {"ACX", "ACY"},
			{"ACN", "ACO"}, {"ZYV", "ZYW"}, {"ADL", "ADM"}, {"ACW", "ACX"}, {"ADD", "ADE"}, {"AEB", "AEC"},
			{"ADG", "ADH"}, {"ACO", "ACP"}, {"AAM", "AAN"}, {"ADB", "ADC"}, {"ZZE", "ZZF"}, {"ZZT", "ZZU"},
			{"ABS", "ABT"}, {"ZXV", "ZXW"}, {"ZYJ", "ZYK"}, {"AAR", "AAS"}, {"AEQ", "ZXS"}, {"ADW", "ADX"},
			{"ZZM", "ZZN"}, {"ACJ", "ACK"}, {"ADR", "ADS"}, {"ABX", "ABY"}, {"ZZO", "ZZP"}, {"ABP", "ABQ"},
			{"ABU", "ABV"}, {"ZXY", "ZXZ"}, {"AAW", "AAX"}, {"ADC", "ADD"}, {"ACM", "ACN"}, {"AAT", "AAU"},
			{"ABJ", "ABK"}, {"ADM", "ADN"}, {"ZYN", "ZYO"}, {"ADI", "ADJ"}, {"ZZW", "ZZX"}, {"ZYH", "ZYI"},
			{"ACU", "ACV"}, {"AEC", "AED"}, {"ABG", "ABH"}, {"AAO", "AAP"}, {"AEF", "AEG"}, {"ACZ", "ADA"},
			{"ZYD", "ZYE"}, {"ZZG", "ZZH"}, {"ABM", "ABN"}, {"ADO", "ADP"}, {"AEI", "AEJ"}, {"ACD", "ACE"},
			{"ZYA", "ZYB"}, {"ACK", "ACL"}, {"AEH", "AEI"}, {"AAZ", "ABA"}, {"AEJ", "AEK"}, {"AAJ", "AAK"},
			{"AEL", "AEM"}, {"ABB", "ABC"}, {"AAA", "AAB"}, {"ZXZ", "ZYA"}, {"ADP", "ADQ"}, {"ZZA", "ZZB"},
			{"ACC", "ACD"}, {"AEG", "AEH"}, {"ACY", "ACZ"}, {"AAU", "AAV"}, {"ACE", "ACF"},
		}},
		{"tickets": [][]string{
			{"RGN", "DAC"}, {"SIN", "CGK"}, {"ZRH", "FCO"}, {"GVA", "MXP"}, {"DUR", "ADD"}, {"AMS", "FRA"},
			{"CLE", "MEX"}, {"SOF", "BEG"}, {"GDL", "CUN"}, {"BHX", "EDI"}, {"ATL", "MIA"}, {"AKL", "CHC"},
			{"PMO", "MAD"}, {"HKG", "TPE"}, {"LOS", "JNB"}, {"LHR", "CDG"}, {"CBR", "BNE"}, {"CHC", "WLG"},
			{"OTP", "SOF"}, {"OSL", "HEL"}, {"MUC", "BER"}, {"BUD", "PRG"}, {"MCO", "TPA"}, {"BOS", "EWR"},
			{"VCE", "NAP"}, {"WAW", "KBP"}, {"VNO", "WAW"}, {"MBA", "SEZ"}, {"TLL", "RIX"}, {"MEX", "GDL"},
			{"CLT", "ATL"}, {"SGN", "KUL"}, {"HND", "CTS"}, {"CPH", "OSL"}, {"BEG", "SJJ"}, {"FOR", "ACC"},
			{"IAH", "DFW"}, {"NAN", "GUM"}, {"CPT", "DUR"}, {"IST", "CAI"}, {"MSP", "ORD"}, {"DPS", "PER"},
			{"BSB", "REC"}, {"CCU", "BKK"}, {"REC", "FOR"}, {"BNE", "AKL"}, {"LAS", "DEN"}, {"GDX", "HNL"},
			{"EZE", "MVD"}, {"LED", "ARN"}, {"KUL", "SIN"}, {"DFW", "PHX"}, {"NRT", "HND"}, {"PER", "SYD"},
			{"LIS", "OPO"}, {"HEL", "TLL"}, {"CMB", "BKI"}, {"HNL", "LAX"}, {"FCO", "ATH"}, {"MIA", "MCO"},
			{"BOG", "LIM"}, {"IAD", "CLT"}, {"PHL", "IAD"}, {"ATH", "IST"}, {"DEN", "MSP"}, {"OPO", "DUB"},
			{"CUN", "HAV"}, {"JFK", "LHR"}, {"YWG", "YYZ"}, {"DUB", "BHX"}, {"MCT", "BOM"}, {"DAC", "KTM"},
			{"ICN", "NRT"}, {"ACC", "LOS"}, {"AUH", "MCT"}, {"GRU", "GIG"}, {"BER", "HAM"}, {"FRA", "ZRH"},
			{"MXP", "VCE"}, {"KHV", "GDX"}, {"YYZ", "YUL"}, {"RIX", "VNO"}, {"LUX", "GVA"}, {"VIE", "BUD"},
			{"SYD", "MEL"}, {"SFO", "SEA"}, {"YUL", "YHZ"}, {"CEB", "RGN"}, {"CGK", "DPS"}, {"PHX", "LAS"},
			{"PTY", "BOG"}, {"MAD", "BCN"}, {"NBO", "MBA"}, {"SVO", "LED"}, {"GIG", "BSB"}, {"YHZ", "BOS"},
			{"CTS", "PVG"}, {"BKK", "SGN"}, {"CDG", "AMS"}, {"DXB", "DOH"}, {"TPA", "MSY"}, {"MSY", "IAH"},
			{"LAX", "SFO"}, {"BKI", "CEB"}, {"YVR", "YYC"}, {"ALA", "DME"}, {"ADD", "NBO"}, {"KTM", "TAS"},
			{"TAS", "ALA"}, {"SCL", "EZE"}, {"HAM", "BRU"}, {"SJJ", "ZAG"}, {"YYC", "YEG"}, {"GUM", "MNL"},
			{"VVO", "KHV"}, {"JNB", "CPT"}, {"NAP", "PMO"}, {"SEA", "YVR"}, {"MNL", "HKG"}, {"ORD", "DTW"},
			{"PEK", "ULN"}, {"YEG", "YWG"}, {"DOH", "AUH"}, {"WLG", "NAN"}, {"PVG", "PEK"}, {"BCN", "LIS"},
			{"KBP", "OTP"}, {"ARN", "CPH"}, {"BOM", "DEL"}, {"MRU", "CMB"}, {"DEL", "CCU"}, {"ULN", "VVO"},
			{"MEL", "CBR"}, {"CAI", "DXB"}, {"DTW", "CLE"}, {"MVD", "GRU"}, {"PRG", "MUC"}, {"HAV", "PTY"},
			{"LIM", "SCL"}, {"TPE", "ICN"}, {"EWR", "PHL"}, {"SEZ", "MRU"}, {"BRU", "LUX"}, {"DME", "SVO"},
			{"ZAG", "VIE"},
		}},
		{"tickets": [][]string{
			{"BLL", "AAL"}, {"VIE", "GRZ"}, {"DEB", "CLJ"}, {"LNZ", "BTS"}, {"CLJ", "OTP"}, {"IEV", "DOK"},
			{"LHR", "CDG"}, {"HAM", "BER"}, {"CDG", "ORY"}, {"WAW", "GDN"}, {"VLC", "IBZ"}, {"SOF", "SKP"},
			{"DOK", "RIX"}, {"ZAG", "LJU"}, {"WRO", "LUG"}, {"DUS", "HAM"}, {"DBV", "SPU"}, {"BER", "DRS"},
			{"FLR", "BLQ"}, {"AAL", "BGO"}, {"TSF", "KSC"}, {"TRN", "MXP"}, {"LJU", "KLU"}, {"INN", "SZG"},
			{"BDS", "CTA"}, {"BGY", "VRN"}, {"LUG", "GOA"}, {"POZ", "WRO"}, {"CAG", "MAD"}, {"BCN", "AGP"},
			{"ARN", "GOT"}, {"BLQ", "TSF"}, {"SVG", "AES"}, {"SZG", "LNZ"}, {"BUD", "DEB"}, {"VRN", "VCE"},
			{"TRS", "FCO"}, {"MRS", "BOD"}, {"NTE", "BES"}, {"IBZ", "PMI"}, {"OUL", "ARN"}, {"TMP", "OUL"},
			{"BSL", "GVA"}, {"VGO", "BIO"}, {"BGO", "OSL"}, {"LYS", "BSL"}, {"PRG", "BRQ"}, {"BRN", "TRN"},
			{"AGP", "SVQ"}, {"SPU", "ZAG"}, {"ORY", "NCE"}, {"SVQ", "LIS"}, {"DRS", "PRG"}, {"BIO", "VLC"},
			{"VCE", "TRS"}, {"SKP", "TIA"}, {"PMI", "MUC"}, {"GDN", "POZ"}, {"NAP", "BDS"}, {"ZRH", "BRN"},
			{"AES", "KEF"}, {"FRA", "DUS"}, {"HEL", "TMP"}, {"OPO", "VGO"}, {"FCO", "NAP"}, {"NCE", "MRS"},
			{"RIX", "TLL"}, {"OSL", "TRD"}, {"MAD", "BCN"}, {"OTP", "SOF"}, {"TRD", "SVG"}, {"BOD", "NTE"},
			{"TIA", "DBV"}, {"PMO", "CAG"}, {"KLU", "INN"}, {"CPH", "BLL"}, {"KSC", "IEV"}, {"BES", "LYS"},
			{"CTA", "PMO"}, {"GOA", "FLR"}, {"BRQ", "VIE"}, {"GVA", "ZRH"}, {"GRZ", "BUD"}, {"BTS", "KRK"},
			{"GOT", "CPH"}, {"KRK", "WAW"}, {"MXP", "BGY"}, {"TLL", "HEL"}, {"MUC", "FRA"}, {"LIS", "OPO"},
		}},
	}
	return payloads
}
